# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'ParkZeus' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'Alamofire-SwiftyJSON'
  pod 'KeychainSwift', '~> 18.0'
  pod 'EVReflection'
  pod 'GoogleMaps', '6.1.0'
  pod 'GooglePlaces', '6.1.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Cosmos', '~> 21.0'
  pod 'Toast-Swift', '~> 5.0.0'
  
end

post_install do |installer|
        installer.pods_project.targets.each do |target|
          target.build_configurations.each do |config|
            config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
            config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          end
        end
      end
